### ISSUE TITLE
future and past emojis

### ISSUE THREAD

**Issue by hodanli** [KerfuffleV2/logseq-plugin-interval-hints#1]
hi

thanks for the plugin. 

can we get an option to change emojis for past and future. that would be useful. 

thanks again.

**Comment by KerfuffleV2** [comment]
You can actually already change it to whatever you want using CSS. For example, add this to `custom.css` in the settings (it's under "Custom theme: `Edit custom.css`":

```css
.lsp-interval-hints-future > .lsp-interval-hints-label::before { content: '[PENDING]'; }
.lsp-interval-hints-future.lsp-interval-hints-short > .lsp-interval-hints-label::before { content: '[SOON]'; }
.lsp-interval-hints-past > .lsp-interval-hints-label::before { content: '[PAST]'; }
.lsp-interval-hints-past.lsp-interval-hints-short > .lsp-interval-hints-label::before { content: '[RECENT]'; }
```

This example also adds a recent past indicator (not defined by the default style). You can also add whatever style information you want in those CSS rules, for example to set a different color background, different font/size, etc.
